gText_Birch_Welcome::
	.string "Greetings Trainers,and welcome\n"
	.string "to Emerald Facility!\p"
	.string "You have chosen,\n"
	.string "or been chosen,\l"
	.string "to enter this advanced battle gauntlet.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Of course, you're all familiar\n"
	.string "with Pokémon.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "As experienced trainers, you'll all know\n"
	.string "that even this lowly Lotad can become a\l"
	.string "a force with the right training and\l"
	.string "battle-hardening.\p"
	.string "Inside Emerald Facility, we strive to\n"
	.string "turn all trainers and Pokémon into strong\l"
	.string "forces with our daily training regimes.\p"
	.string "You will sleep in our dorms, eat in our\n"
	.string "canteen, shop in our mart, and catch\l"
	.string "Pokémon in our private preserve,\l"
	.string "where Pokémon from every known region\l"
	.string "of the world can be found and caught.\p"
	.string "Each of you will have an equal\n"
	.string "opportunity to battle our fleet \l"
	.string "of diverse trainer bots\l"
	.string "- and of course each other -\l"
	.string "in pursuit of our 8 Gym badges.\p"
	.string "Those who succeed in defeating our\n"
	.string "gyms will survive to challenge our\l"
	.string "Elite Four and claim the title\l"
	.string "of Champion!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Please consent to enter Emerald Facility\n"
	.string "by telling us a bit about yourself.\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Please select your gender.$"

gText_Birch_WhatsYourName::
	.string "Confirmed.\n"
	.string "What is your name?$"

gText_Birch_SoItsPlayer::
	.string "Is {PLAYER}{KUN} correct?$"

gText_Birch_YourePlayer::
	.string "Confirmed.\p"
	.string "Thank you for signing our comprehensive\n"
	.string "waiver form, {PLAYER}{KUN}.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Please enter through the checkpoint\n"
	.string "and discover your starting Pokémon.\l"
	.string "Randomly chosen from a group of\l"
	.string "powerful Pokémon from across\l"
	.string "the world, each of these starters are\l"
	.string "very special.\p"
	.string "I should know, I selected them myself!\p"
	.string "You may pick up a Pokédex, some\n"
	.string "basic items like potions and Pokeballs,\l"
	.string "and a pair of non-marking Running Shoes\l"
	.string "from the attendants.\p"
	.string "Train hard and battle even harder.\n"
	.string "I'll be watching!\p"
	.string "$"
