#include "global.h"
#include "wild_encounter.h"
#include "pokemon.h"
#include "metatile_behavior.h"
#include "fieldmap.h"
#include "random.h"
#include "field_player_avatar.h"
#include "event_data.h"
#include "safari_zone.h"
#include "overworld.h"
#include "pokeblock.h"
#include "battle_setup.h"
#include "roamer.h"
#include "tv.h"
#include "link.h"
#include "script.h"
#include "battle_debug.h"
#include "battle_pike.h"
#include "battle_pyramid.h"
#include "constants/abilities.h"
#include "constants/game_stat.h"
#include "constants/item.h"
#include "constants/items.h"
#include "constants/layouts.h"
#include "constants/weather.h"

extern const u8 EventScript_SprayWoreOff[];

#define MAX_ENCOUNTER_RATE 2880

#define NUM_FEEBAS_SPOTS 6

// Number of accessible fishing spots in each section of Route 119
// Each section is an area of the route between the y coordinates in sRoute119WaterTileData
#define NUM_FISHING_SPOTS_1 131
#define NUM_FISHING_SPOTS_2 167
#define NUM_FISHING_SPOTS_3 149
#define NUM_FISHING_SPOTS (NUM_FISHING_SPOTS_1 + NUM_FISHING_SPOTS_2 + NUM_FISHING_SPOTS_3)

enum {
    WILD_AREA_LAND,
    WILD_AREA_WATER,
    WILD_AREA_ROCKS,
    WILD_AREA_FISHING,
};

#define WILD_CHECK_REPEL    (1 << 0)
#define WILD_CHECK_KEEN_EYE (1 << 1)

#define HEADER_NONE 0xFFFF

static u16 FeebasRandom(void);
static void FeebasSeedRng(u16 seed);
static bool8 IsWildLevelAllowedByRepel(u8 level);
static void ApplyFluteEncounterRateMod(u32 *encRate);
static void ApplyCleanseTagEncounterRateMod(u32 *encRate);
static u8 GetMaxLevelOfSpeciesInWildTable(const struct WildPokemon *wildMon, u16 species, u8 area);
#ifdef BUGFIX
static bool8 TryGetAbilityInfluencedWildMonIndex(const struct WildPokemon *wildMon, u8 type, u16 ability, u8 *monIndex, u32 size);
#else
static bool8 TryGetAbilityInfluencedWildMonIndex(const struct WildPokemon *wildMon, u8 type, u16 ability, u8 *monIndex);
#endif
static bool8 IsAbilityAllowingEncounter(u8 level);

EWRAM_DATA static u8 sWildEncountersDisabled = 0;
EWRAM_DATA static u32 sFeebasRngValue = 0;
EWRAM_DATA bool8 gIsFishingEncounter = 0;
EWRAM_DATA bool8 gIsSurfingEncounter = 0;

#include "data/wild_encounters.h"

static const struct WildPokemon sWildFeebas = {20, 25, SPECIES_FEEBAS};

static const u16 sRoute119WaterTileData[] =
{
//yMin, yMax, numSpots in previous sections
     0,  45,  0,
    46,  91,  NUM_FISHING_SPOTS_1,
    92, 139,  NUM_FISHING_SPOTS_1 + NUM_FISHING_SPOTS_2,
};

void DisableWildEncounters(bool8 disabled)
{
    sWildEncountersDisabled = disabled;
}

// Each fishing spot on Route 119 is given a number between 1 and NUM_FISHING_SPOTS inclusive.
// The number is determined by counting the valid fishing spots left to right top to bottom.
// The map is divided into three sections, with each section having a pre-counted number of
// fishing spots to start from to avoid counting a large number of spots at the bottom of the map.
// Note that a spot is considered valid if it is surfable and not a waterfall. To exclude all
// of the inaccessible water metatiles (so that they can't be selected as a Feebas spot) they
// use a different metatile that isn't actually surfable because it has MB_NORMAL instead.
// This function is given the coordinates and section of a fishing spot and returns which number it is.
static u16 GetFeebasFishingSpotId(s16 targetX, s16 targetY, u8 section)
{
    u16 x, y;
    u16 yMin = sRoute119WaterTileData[section * 3 + 0];
    u16 yMax = sRoute119WaterTileData[section * 3 + 1];
    u16 spotId = sRoute119WaterTileData[section * 3 + 2];

    for (y = yMin; y <= yMax; y++)
    {
        for (x = 0; x < gMapHeader.mapLayout->width; x++)
        {
            u8 behavior = MapGridGetMetatileBehaviorAt(x + MAP_OFFSET, y + MAP_OFFSET);
            if (MetatileBehavior_IsSurfableAndNotWaterfall(behavior) == TRUE)
            {
                spotId++;
                if (targetX == x && targetY == y)
                    return spotId;
            }
        }
    }
    return spotId + 1;
}

static bool8 CheckFeebas(void)
{
    u8 i;
    u16 feebasSpots[NUM_FEEBAS_SPOTS];
    s16 x, y;
    u8 route119Section = 0;
    u16 spotId;

    if (gSaveBlock1Ptr->location.mapGroup == MAP_GROUP(ROUTE119)
     && gSaveBlock1Ptr->location.mapNum == MAP_NUM(ROUTE119))
    {
        GetXYCoordsOneStepInFrontOfPlayer(&x, &y);
        x -= MAP_OFFSET;
        y -= MAP_OFFSET;

        // Get which third of the map the player is in
        if (y >= sRoute119WaterTileData[3 * 0 + 0] && y <= sRoute119WaterTileData[3 * 0 + 1])
            route119Section = 0;
        if (y >= sRoute119WaterTileData[3 * 1 + 0] && y <= sRoute119WaterTileData[3 * 1 + 1])
            route119Section = 1;
        if (y >= sRoute119WaterTileData[3 * 2 + 0] && y <= sRoute119WaterTileData[3 * 2 + 1])
            route119Section = 2;

        // 50% chance of encountering Feebas (assuming this is a Feebas spot)
        if (Random() % 100 > 49)
            return FALSE;

        FeebasSeedRng(gSaveBlock1Ptr->dewfordTrends[0].rand);

        // Assign each Feebas spot to a random fishing spot.
        // Randomness is fixed depending on the seed above.
        for (i = 0; i != NUM_FEEBAS_SPOTS;)
        {
            feebasSpots[i] = FeebasRandom() % NUM_FISHING_SPOTS;
            if (feebasSpots[i] == 0)
                feebasSpots[i] = NUM_FISHING_SPOTS;

            // < 1 below is a pointless check, it will never be TRUE.
            // >= 4 to skip fishing spots 1-3, because these are inaccessible
            // spots at the top of the map, at (9,7), (7,13), and (15,16).
            // The first accessible fishing spot is spot 4 at (18,18).
            if (feebasSpots[i] < 1 || feebasSpots[i] >= 4)
                i++;
        }

        // Check which fishing spot the player is at, and see if
        // it matches any of the Feebas spots.
        spotId = GetFeebasFishingSpotId(x, y, route119Section);
        for (i = 0; i < NUM_FEEBAS_SPOTS; i++)
        {
            if (spotId == feebasSpots[i])
                return TRUE;
        }
    }
    return FALSE;
}

static u16 FeebasRandom(void)
{
    sFeebasRngValue = ISO_RANDOMIZE2(sFeebasRngValue);
    return sFeebasRngValue >> 16;
}

static void FeebasSeedRng(u16 seed)
{
    sFeebasRngValue = seed;
}

// LAND_WILD_COUNT
static u8 ChooseWildMonIndex_Land(void)
{
    u8 wildMonIndex = 0;
    bool8 swap = FALSE;
    u8 rand = Random() % ENCOUNTER_CHANCE_LAND_MONS_TOTAL;

    if (rand < ENCOUNTER_CHANCE_LAND_MONS_SLOT_0)
        wildMonIndex = 0;
    else if (rand >= ENCOUNTER_CHANCE_LAND_MONS_SLOT_0 && rand < ENCOUNTER_CHANCE_LAND_MONS_SLOT_1)
        wildMonIndex = 1;
    else if (rand >= ENCOUNTER_CHANCE_LAND_MONS_SLOT_1 && rand < ENCOUNTER_CHANCE_LAND_MONS_SLOT_2)
        wildMonIndex = 2;
    else if (rand >= ENCOUNTER_CHANCE_LAND_MONS_SLOT_2 && rand < ENCOUNTER_CHANCE_LAND_MONS_SLOT_3)
        wildMonIndex = 3;
    else if (rand >= ENCOUNTER_CHANCE_LAND_MONS_SLOT_3 && rand < ENCOUNTER_CHANCE_LAND_MONS_SLOT_4)
        wildMonIndex = 4;
    else if (rand >= ENCOUNTER_CHANCE_LAND_MONS_SLOT_4 && rand < ENCOUNTER_CHANCE_LAND_MONS_SLOT_5)
        wildMonIndex = 5;
    else if (rand >= ENCOUNTER_CHANCE_LAND_MONS_SLOT_5 && rand < ENCOUNTER_CHANCE_LAND_MONS_SLOT_6)
        wildMonIndex = 6;
    else if (rand >= ENCOUNTER_CHANCE_LAND_MONS_SLOT_6 && rand < ENCOUNTER_CHANCE_LAND_MONS_SLOT_7)
        wildMonIndex = 7;
    else if (rand >= ENCOUNTER_CHANCE_LAND_MONS_SLOT_7 && rand < ENCOUNTER_CHANCE_LAND_MONS_SLOT_8)
        wildMonIndex = 8;
    else if (rand >= ENCOUNTER_CHANCE_LAND_MONS_SLOT_8 && rand < ENCOUNTER_CHANCE_LAND_MONS_SLOT_9)
        wildMonIndex = 9;
    else if (rand >= ENCOUNTER_CHANCE_LAND_MONS_SLOT_9 && rand < ENCOUNTER_CHANCE_LAND_MONS_SLOT_10)
        wildMonIndex = 10;
    else
        wildMonIndex = 11;

    if (LURE_STEP_COUNT != 0 && (Random() % 10 < 2))
        swap = TRUE;

    if (swap)
        wildMonIndex = 11 - wildMonIndex;

    return wildMonIndex;
}

// ROCK_WILD_COUNT / WATER_WILD_COUNT
static u8 ChooseWildMonIndex_WaterRock(void)
{
    u8 wildMonIndex = 0;
    bool8 swap = FALSE;
    u8 rand = Random() % ENCOUNTER_CHANCE_WATER_MONS_TOTAL;

    if (rand < ENCOUNTER_CHANCE_WATER_MONS_SLOT_0)
        wildMonIndex = 0;
    else if (rand >= ENCOUNTER_CHANCE_WATER_MONS_SLOT_0 && rand < ENCOUNTER_CHANCE_WATER_MONS_SLOT_1)
        wildMonIndex = 1;
    else if (rand >= ENCOUNTER_CHANCE_WATER_MONS_SLOT_1 && rand < ENCOUNTER_CHANCE_WATER_MONS_SLOT_2)
        wildMonIndex = 2;
    else if (rand >= ENCOUNTER_CHANCE_WATER_MONS_SLOT_2 && rand < ENCOUNTER_CHANCE_WATER_MONS_SLOT_3)
        wildMonIndex = 3;
    else
        wildMonIndex = 4;

    if (LURE_STEP_COUNT != 0 && (Random() % 10 < 2))
        swap = TRUE;

    if (swap)
        wildMonIndex = 4 - wildMonIndex;

    return wildMonIndex;
}

// FISH_WILD_COUNT
static u8 ChooseWildMonIndex_Fishing(u8 rod)
{
    u8 wildMonIndex = 0;
    bool8 swap = FALSE;
    u8 rand = Random() % max(max(ENCOUNTER_CHANCE_FISHING_MONS_OLD_ROD_TOTAL, ENCOUNTER_CHANCE_FISHING_MONS_GOOD_ROD_TOTAL),
                             ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_TOTAL);

    if (LURE_STEP_COUNT != 0 && (Random() % 10 < 2))
        swap = TRUE;

    switch (rod)
    {
    case OLD_ROD:
        if (rand < ENCOUNTER_CHANCE_FISHING_MONS_OLD_ROD_SLOT_0)
            wildMonIndex = 0;
        else
            wildMonIndex = 1;

        if (swap)
            wildMonIndex = 1 - wildMonIndex;
        break;
    case GOOD_ROD:
        if (rand < ENCOUNTER_CHANCE_FISHING_MONS_GOOD_ROD_SLOT_2)
            wildMonIndex = 2;
        if (rand >= ENCOUNTER_CHANCE_FISHING_MONS_GOOD_ROD_SLOT_2 && rand < ENCOUNTER_CHANCE_FISHING_MONS_GOOD_ROD_SLOT_3)
            wildMonIndex = 3;
        if (rand >= ENCOUNTER_CHANCE_FISHING_MONS_GOOD_ROD_SLOT_3 && rand < ENCOUNTER_CHANCE_FISHING_MONS_GOOD_ROD_SLOT_4)
            wildMonIndex = 4;

        if (swap)
            wildMonIndex = 6 - wildMonIndex;
        break;
    case SUPER_ROD:
        if (rand < ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_5)
            wildMonIndex = 5;
        if (rand >= ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_5 && rand < ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_6)
            wildMonIndex = 6;
        if (rand >= ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_6 && rand < ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_7)
            wildMonIndex = 7;
        if (rand >= ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_7 && rand < ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_8)
            wildMonIndex = 8;
        if (rand >= ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_8 && rand < ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_9)
            wildMonIndex = 9;

        if (swap)
            wildMonIndex = 14 - wildMonIndex;
        break;
    }
    return wildMonIndex;
}

static u8 ChooseWildMonLevel(const struct WildPokemon *wildPokemon, u8 wildMonIndex, u8 area)
{
    u8 min;
    u8 max;
    u8 range;
    u8 rand;

    if (LURE_STEP_COUNT == 0)
    {
       u8 fixedLVL = 0;
	{
	if (GetMonData(&gPlayerParty[5], MON_DATA_SPECIES) != SPECIES_NONE)
		fixedLVL = (GetMonData(&gPlayerParty[0], MON_DATA_LEVEL) + GetMonData(&gPlayerParty[1], MON_DATA_LEVEL) + GetMonData(&gPlayerParty[2], MON_DATA_LEVEL) + GetMonData(&gPlayerParty[3], MON_DATA_LEVEL) + GetMonData(&gPlayerParty[4], MON_DATA_LEVEL) + GetMonData(&gPlayerParty[5], MON_DATA_LEVEL)) / 6;
	else if ((GetMonData(&gPlayerParty[5], MON_DATA_SPECIES) == SPECIES_NONE) && (GetMonData(&gPlayerParty[4], MON_DATA_SPECIES) != SPECIES_NONE))
			fixedLVL = (GetMonData(&gPlayerParty[0], MON_DATA_LEVEL)+GetMonData(&gPlayerParty[1], MON_DATA_LEVEL)+GetMonData(&gPlayerParty[2], MON_DATA_LEVEL)+GetMonData(&gPlayerParty[3], MON_DATA_LEVEL)+GetMonData(&gPlayerParty[4], MON_DATA_LEVEL)) / 5;
		else if ((GetMonData(&gPlayerParty[4], MON_DATA_SPECIES) == SPECIES_NONE) && (GetMonData(&gPlayerParty[3], MON_DATA_SPECIES) != SPECIES_NONE))
			fixedLVL = (GetMonData(&gPlayerParty[0], MON_DATA_LEVEL)+GetMonData(&gPlayerParty[1], MON_DATA_LEVEL)+GetMonData(&gPlayerParty[2], MON_DATA_LEVEL)+GetMonData(&gPlayerParty[3], MON_DATA_LEVEL)) / 4;
			else if ((GetMonData(&gPlayerParty[3], MON_DATA_SPECIES) == SPECIES_NONE) && (GetMonData(&gPlayerParty[2], MON_DATA_SPECIES) != SPECIES_NONE))
				fixedLVL = (GetMonData(&gPlayerParty[0], MON_DATA_LEVEL)+GetMonData(&gPlayerParty[1], MON_DATA_LEVEL)+GetMonData(&gPlayerParty[2], MON_DATA_LEVEL)) / 3;
				else if ((GetMonData(&gPlayerParty[2], MON_DATA_SPECIES) == SPECIES_NONE) && (GetMonData(&gPlayerParty[1], MON_DATA_SPECIES) != SPECIES_NONE))
					fixedLVL = (GetMonData(&gPlayerParty[0], MON_DATA_LEVEL)+GetMonData(&gPlayerParty[1], MON_DATA_LEVEL)) / 2;
					else if ((GetMonData(&gPlayerParty[1], MON_DATA_SPECIES) == SPECIES_NONE) && (GetMonData(&gPlayerParty[0], MON_DATA_SPECIES) != SPECIES_NONE))
						fixedLVL = GetMonData(&gPlayerParty[0], MON_DATA_LEVEL);
	}

    // Make sure minimum level is less than maximum level
    {
        min = fixedLVL-5;
        max = fixedLVL+1;
    } 
	if (min <= 0)
		min = 1;
    range = max - min + 1;
    rand = Random() % range;

        // check ability for max level mon
        if (!GetMonData(&gPlayerParty[0], MON_DATA_SANITY_IS_EGG))
        {
            u16 ability = GetMonAbility(&gPlayerParty[0]);
            if (ability == ABILITY_HUSTLE || ability == ABILITY_VITAL_SPIRIT || ability == ABILITY_PRESSURE)
            {
                if (Random() % 2 == 0)
                    return max;

                if (rand != 0)
                    rand--;
            }
        }
        return min + rand;
    }
    else
    {
        // Looks for the max level of all slots that share the same species as the selected slot.
        max = GetMaxLevelOfSpeciesInWildTable(wildPokemon, wildPokemon[wildMonIndex].species, area);
        if (max > 0)
            return max + 1;
        else // Failsafe
            return wildPokemon[wildMonIndex].maxLevel + 1;
    }
}

static u16 GetCurrentMapWildMonHeaderId(void)
{
    u16 i;

    for (i = 0; ; i++)
    {
        const struct WildPokemonHeader *wildHeader = &gWildMonHeaders[i];
        if (wildHeader->mapGroup == MAP_GROUP(UNDEFINED))
            break;

        if (gWildMonHeaders[i].mapGroup == gSaveBlock1Ptr->location.mapGroup &&
            gWildMonHeaders[i].mapNum == gSaveBlock1Ptr->location.mapNum)
        {
            if (gSaveBlock1Ptr->location.mapGroup == MAP_GROUP(ALTERING_CAVE) &&
                gSaveBlock1Ptr->location.mapNum == MAP_NUM(ALTERING_CAVE))
            {
                u16 alteringCaveId = VarGet(VAR_ALTERING_CAVE_WILD_SET);
                if (alteringCaveId >= NUM_ALTERING_CAVE_TABLES)
                    alteringCaveId = 0;

                i += alteringCaveId;
            }

            return i;
        }
    }

    return HEADER_NONE;
}

u8 PickWildMonNature(void)
{
    u8 i;
    struct Pokeblock *safariPokeblock;
    u8 natures[NUM_NATURES];

    if (GetSafariZoneFlag() == TRUE && Random() % 100 < 80)
    {
        safariPokeblock = SafariZoneGetActivePokeblock();
        if (safariPokeblock != NULL)
        {
            for (i = 0; i < NUM_NATURES; i++)
                natures[i] = i;
            Shuffle(natures, NUM_NATURES, sizeof(natures[0]));
            for (i = 0; i < NUM_NATURES; i++)
            {
                if (PokeblockGetGain(natures[i], safariPokeblock) > 0)
                    return natures[i];
            }
        }
    }
    // check synchronize for a Pokémon with the same ability
    if (OW_SYNCHRONIZE_NATURE < GEN_9
        && !GetMonData(&gPlayerParty[0], MON_DATA_SANITY_IS_EGG)
        && GetMonAbility(&gPlayerParty[0]) == ABILITY_SYNCHRONIZE
        && (OW_SYNCHRONIZE_NATURE == GEN_8 || Random() % 2 == 0))
    {
        return GetMonData(&gPlayerParty[0], MON_DATA_PERSONALITY) % NUM_NATURES;
    }

    // random nature
    return Random() % NUM_NATURES;

}

static const u16 gRandomMonListArray[] =
{
SPECIES_BULBASAUR,
SPECIES_IVYSAUR,
SPECIES_VENUSAUR,
SPECIES_CHARMANDER,
SPECIES_CHARMELEON,
SPECIES_CHARIZARD,
SPECIES_SQUIRTLE,
SPECIES_WARTORTLE,
SPECIES_BLASTOISE,
SPECIES_CATERPIE,
SPECIES_METAPOD,
SPECIES_BUTTERFREE,
SPECIES_WEEDLE,
SPECIES_KAKUNA,
SPECIES_BEEDRILL,
SPECIES_PIDGEY,
SPECIES_PIDGEOTTO,
SPECIES_PIDGEOT,
SPECIES_RATTATA,
SPECIES_RATICATE,
SPECIES_RATTATA_ALOLAN,
SPECIES_RATICATE_ALOLAN,
SPECIES_SPEAROW,
SPECIES_FEAROW,
SPECIES_EKANS,
SPECIES_ARBOK,
SPECIES_PICHU,
SPECIES_PICHU_SPIKY_EARED,
SPECIES_PIKACHU,
SPECIES_PIKACHU_COSPLAY,
SPECIES_PIKACHU_PARTNER,
SPECIES_RAICHU,
SPECIES_RAICHU_ALOLAN,
SPECIES_SANDSHREW,
SPECIES_SANDSLASH,
SPECIES_SANDSHREW_ALOLAN,
SPECIES_SANDSLASH_ALOLAN,
SPECIES_NIDORAN_F,
SPECIES_NIDORINA,
SPECIES_NIDOQUEEN,
SPECIES_NIDORAN_M,
SPECIES_NIDORINO,
SPECIES_NIDOKING,
SPECIES_CLEFFA,
SPECIES_CLEFAIRY,
SPECIES_CLEFABLE,
SPECIES_VULPIX,
SPECIES_NINETALES,
SPECIES_VULPIX_ALOLAN,
SPECIES_NINETALES_ALOLAN,
SPECIES_IGGLYBUFF,
SPECIES_JIGGLYPUFF,
SPECIES_WIGGLYTUFF,
SPECIES_ZUBAT,
SPECIES_GOLBAT,
SPECIES_CROBAT,
SPECIES_ODDISH,
SPECIES_GLOOM,
SPECIES_VILEPLUME,
SPECIES_BELLOSSOM,
SPECIES_PARAS,
SPECIES_PARASECT,
SPECIES_VENONAT,
SPECIES_VENOMOTH,
SPECIES_DIGLETT,
SPECIES_DUGTRIO,
SPECIES_DIGLETT_ALOLAN,
SPECIES_DUGTRIO_ALOLAN,
SPECIES_MEOWTH,
SPECIES_PERSIAN,
SPECIES_MEOWTH_ALOLAN,
SPECIES_PERSIAN_ALOLAN,
SPECIES_MEOWTH_GALARIAN,
SPECIES_PERRSERKER,
SPECIES_PSYDUCK,
SPECIES_GOLDUCK,
SPECIES_MANKEY,
SPECIES_PRIMEAPE,
SPECIES_ANNIHILAPE,
SPECIES_GROWLITHE,
SPECIES_ARCANINE,
SPECIES_GROWLITHE_HISUIAN,
SPECIES_ARCANINE_HISUIAN,
SPECIES_POLIWAG,
SPECIES_POLIWHIRL,
SPECIES_POLIWRATH,
SPECIES_POLITOED,
SPECIES_ABRA,
SPECIES_KADABRA,
SPECIES_ALAKAZAM,
SPECIES_MACHOP,
SPECIES_MACHOKE,
SPECIES_MACHAMP,
SPECIES_BELLSPROUT,
SPECIES_WEEPINBELL,
SPECIES_VICTREEBEL,
SPECIES_TENTACOOL,
SPECIES_TENTACRUEL,
SPECIES_GEODUDE,
SPECIES_GRAVELER,
SPECIES_GOLEM,
SPECIES_GEODUDE_ALOLAN,
SPECIES_GRAVELER_ALOLAN,
SPECIES_GOLEM_ALOLAN,
SPECIES_PONYTA,
SPECIES_RAPIDASH,
SPECIES_PONYTA_GALARIAN,
SPECIES_RAPIDASH_GALARIAN,
SPECIES_SLOWPOKE,
SPECIES_SLOWBRO,
SPECIES_SLOWKING,
SPECIES_SLOWPOKE_GALARIAN,
SPECIES_SLOWBRO_GALARIAN,
SPECIES_SLOWKING_GALARIAN,
SPECIES_MAGNEMITE,
SPECIES_MAGNETON,
SPECIES_MAGNEZONE,
SPECIES_FARFETCHD,
SPECIES_FARFETCHD_GALARIAN,
SPECIES_SIRFETCHD,
SPECIES_DODUO,
SPECIES_DODRIO,
SPECIES_SEEL,
SPECIES_DEWGONG,
SPECIES_GRIMER,
SPECIES_MUK,
SPECIES_GRIMER_ALOLAN,
SPECIES_MUK_ALOLAN,
SPECIES_SHELLDER,
SPECIES_CLOYSTER,
SPECIES_GASTLY,
SPECIES_HAUNTER,
SPECIES_GENGAR,
SPECIES_ONIX,
SPECIES_STEELIX,
SPECIES_DROWZEE,
SPECIES_HYPNO,
SPECIES_KRABBY,
SPECIES_KINGLER,
SPECIES_VOLTORB,
SPECIES_ELECTRODE,
SPECIES_VOLTORB_HISUIAN,
SPECIES_ELECTRODE_HISUIAN,
SPECIES_EXEGGCUTE,
SPECIES_EXEGGUTOR,
SPECIES_EXEGGUTOR_ALOLAN,
SPECIES_CUBONE,
SPECIES_MAROWAK,
SPECIES_MAROWAK_ALOLAN,
SPECIES_MAROWAK_ALOLAN_TOTEM,
SPECIES_TYROGUE,
SPECIES_HITMONLEE,
SPECIES_HITMONCHAN,
SPECIES_HITMONTOP,
SPECIES_LICKITUNG,
SPECIES_LICKILICKY,
SPECIES_KOFFING,
SPECIES_WEEZING,
SPECIES_WEEZING_GALARIAN,
SPECIES_RHYHORN,
SPECIES_RHYDON,
SPECIES_RHYPERIOR,
SPECIES_HAPPINY,
SPECIES_CHANSEY,
SPECIES_BLISSEY,
SPECIES_TANGELA,
SPECIES_TANGROWTH,
SPECIES_KANGASKHAN,
SPECIES_HORSEA,
SPECIES_SEADRA,
SPECIES_KINGDRA,
SPECIES_GOLDEEN,
SPECIES_SEAKING,
SPECIES_STARYU,
SPECIES_STARMIE,
SPECIES_MIME_JR,
SPECIES_MR_MIME,
SPECIES_MR_MIME_GALARIAN,
SPECIES_MR_RIME,
SPECIES_SCYTHER,
SPECIES_SCIZOR,
SPECIES_KLEAVOR,
SPECIES_SMOOCHUM,
SPECIES_JYNX,
SPECIES_ELEKID,
SPECIES_ELECTABUZZ,
SPECIES_ELECTIVIRE,
SPECIES_MAGBY,
SPECIES_MAGMAR,
SPECIES_MAGMORTAR,
SPECIES_PINSIR,
SPECIES_TAUROS,
SPECIES_TAUROS_PALDEAN_COMBAT_BREED,
SPECIES_TAUROS_PALDEAN_BLAZE_BREED,
SPECIES_TAUROS_PALDEAN_AQUA_BREED,
SPECIES_MAGIKARP,
SPECIES_GYARADOS,
SPECIES_LAPRAS,
SPECIES_DITTO,
SPECIES_EEVEE,
SPECIES_EEVEE_PARTNER,
SPECIES_VAPOREON,
SPECIES_JOLTEON,
SPECIES_FLAREON,
SPECIES_ESPEON,
SPECIES_UMBREON,
SPECIES_LEAFEON,
SPECIES_GLACEON,
SPECIES_SYLVEON,
SPECIES_PORYGON,
SPECIES_PORYGON2,
SPECIES_PORYGON_Z,
SPECIES_OMANYTE,
SPECIES_OMASTAR,
SPECIES_KABUTO,
SPECIES_KABUTOPS,
SPECIES_AERODACTYL,
SPECIES_MUNCHLAX,
SPECIES_SNORLAX,
SPECIES_ARTICUNO,
SPECIES_ARTICUNO_GALARIAN,
SPECIES_ZAPDOS,
SPECIES_ZAPDOS_GALARIAN,
SPECIES_MOLTRES,
SPECIES_MOLTRES_GALARIAN,
SPECIES_DRATINI,
SPECIES_DRAGONAIR,
SPECIES_DRAGONITE,
SPECIES_MEWTWO,
SPECIES_MEW,
SPECIES_CHIKORITA,
SPECIES_BAYLEEF,
SPECIES_MEGANIUM,
SPECIES_CYNDAQUIL,
SPECIES_QUILAVA,
SPECIES_TYPHLOSION,
SPECIES_TYPHLOSION_HISUIAN,
SPECIES_TOTODILE,
SPECIES_CROCONAW,
SPECIES_FERALIGATR,
SPECIES_SENTRET,
SPECIES_FURRET,
SPECIES_HOOTHOOT,
SPECIES_NOCTOWL,
SPECIES_LEDYBA,
SPECIES_LEDIAN,
SPECIES_SPINARAK,
SPECIES_ARIADOS,
SPECIES_CHINCHOU,
SPECIES_LANTURN,
SPECIES_TOGEPI,
SPECIES_TOGETIC,
SPECIES_TOGEKISS,
SPECIES_NATU,
SPECIES_XATU,
SPECIES_MAREEP,
SPECIES_FLAAFFY,
SPECIES_AMPHAROS,
SPECIES_AZURILL,
SPECIES_MARILL,
SPECIES_AZUMARILL,
SPECIES_BONSLY,
SPECIES_SUDOWOODO,
SPECIES_HOPPIP,
SPECIES_SKIPLOOM,
SPECIES_JUMPLUFF,
SPECIES_AIPOM,
SPECIES_AMBIPOM,
SPECIES_SUNKERN,
SPECIES_SUNFLORA,
SPECIES_YANMA,
SPECIES_YANMEGA,
SPECIES_WOOPER,
SPECIES_QUAGSIRE,
SPECIES_WOOPER_PALDEAN,
SPECIES_CLODSIRE,
SPECIES_MURKROW,
SPECIES_HONCHKROW,
SPECIES_MISDREAVUS,
SPECIES_MISMAGIUS,
SPECIES_UNOWN,
SPECIES_UNOWN_B,
SPECIES_UNOWN_C,
SPECIES_UNOWN_D,
SPECIES_UNOWN_E,
SPECIES_UNOWN_F,
SPECIES_UNOWN_G,
SPECIES_UNOWN_H,
SPECIES_UNOWN_I,
SPECIES_UNOWN_J,
SPECIES_UNOWN_K,
SPECIES_UNOWN_L,
SPECIES_UNOWN_M,
SPECIES_UNOWN_N,
SPECIES_UNOWN_O,
SPECIES_UNOWN_P,
SPECIES_UNOWN_Q,
SPECIES_UNOWN_R,
SPECIES_UNOWN_S,
SPECIES_UNOWN_T,
SPECIES_UNOWN_U,
SPECIES_UNOWN_V,
SPECIES_UNOWN_W,
SPECIES_UNOWN_X,
SPECIES_UNOWN_Y,
SPECIES_UNOWN_Z,
SPECIES_UNOWN_EMARK,
SPECIES_UNOWN_QMARK,
SPECIES_WYNAUT,
SPECIES_WOBBUFFET,
SPECIES_GIRAFARIG,
SPECIES_FARIGIRAF,
SPECIES_PINECO,
SPECIES_FORRETRESS,
SPECIES_DUNSPARCE,
SPECIES_DUDUNSPARCE_TWO_SEGMENT,
SPECIES_DUDUNSPARCE_THREE_SEGMENT,
SPECIES_GLIGAR,
SPECIES_GLISCOR,
SPECIES_SNUBBULL,
SPECIES_GRANBULL,
SPECIES_QWILFISH,
SPECIES_QWILFISH_HISUIAN,
SPECIES_OVERQWIL,
SPECIES_SHUCKLE,
SPECIES_HERACROSS,
SPECIES_SNEASEL,
SPECIES_WEAVILE,
SPECIES_SNEASEL_HISUIAN,
SPECIES_SNEASLER,
SPECIES_TEDDIURSA,
SPECIES_URSARING,
SPECIES_URSALUNA,
SPECIES_URSALUNA_BLOODMOON,
SPECIES_SLUGMA,
SPECIES_MAGCARGO,
SPECIES_SWINUB,
SPECIES_PILOSWINE,
SPECIES_MAMOSWINE,
SPECIES_CORSOLA,
SPECIES_CORSOLA_GALARIAN,
SPECIES_CURSOLA,
SPECIES_REMORAID,
SPECIES_OCTILLERY,
SPECIES_DELIBIRD,
SPECIES_MANTYKE,
SPECIES_MANTINE,
SPECIES_SKARMORY,
SPECIES_HOUNDOUR,
SPECIES_HOUNDOOM,
SPECIES_PHANPY,
SPECIES_DONPHAN,
SPECIES_STANTLER,
SPECIES_WYRDEER,
SPECIES_SMEARGLE,
SPECIES_MILTANK,
SPECIES_RAIKOU,
SPECIES_ENTEI,
SPECIES_SUICUNE,
SPECIES_LARVITAR,
SPECIES_PUPITAR,
SPECIES_TYRANITAR,
SPECIES_LUGIA,
SPECIES_HO_OH,
SPECIES_CELEBI,
SPECIES_TREECKO,
SPECIES_GROVYLE,
SPECIES_SCEPTILE,
SPECIES_TORCHIC,
SPECIES_COMBUSKEN,
SPECIES_BLAZIKEN,
SPECIES_MUDKIP,
SPECIES_MARSHTOMP,
SPECIES_SWAMPERT,
SPECIES_POOCHYENA,
SPECIES_MIGHTYENA,
SPECIES_ZIGZAGOON,
SPECIES_LINOONE,
SPECIES_ZIGZAGOON_GALARIAN,
SPECIES_LINOONE_GALARIAN,
SPECIES_OBSTAGOON,
SPECIES_WURMPLE,
SPECIES_SILCOON,
SPECIES_BEAUTIFLY,
SPECIES_CASCOON,
SPECIES_DUSTOX,
SPECIES_LOTAD,
SPECIES_LOMBRE,
SPECIES_LUDICOLO,
SPECIES_SEEDOT,
SPECIES_NUZLEAF,
SPECIES_SHIFTRY,
SPECIES_TAILLOW,
SPECIES_SWELLOW,
SPECIES_WINGULL,
SPECIES_PELIPPER,
SPECIES_RALTS,
SPECIES_KIRLIA,
SPECIES_GARDEVOIR,
SPECIES_GALLADE,
SPECIES_SURSKIT,
SPECIES_MASQUERAIN,
SPECIES_SHROOMISH,
SPECIES_BRELOOM,
SPECIES_SLAKOTH,
SPECIES_VIGOROTH,
SPECIES_SLAKING,
SPECIES_NINCADA,
SPECIES_NINJASK,
SPECIES_SHEDINJA,
SPECIES_WHISMUR,
SPECIES_LOUDRED,
SPECIES_EXPLOUD,
SPECIES_MAKUHITA,
SPECIES_HARIYAMA,
SPECIES_NOSEPASS,
SPECIES_PROBOPASS,
SPECIES_SKITTY,
SPECIES_DELCATTY,
SPECIES_SABLEYE,
SPECIES_MAWILE,
SPECIES_ARON,
SPECIES_LAIRON,
SPECIES_AGGRON,
SPECIES_MEDITITE,
SPECIES_MEDICHAM,
SPECIES_ELECTRIKE,
SPECIES_MANECTRIC,
SPECIES_PLUSLE,
SPECIES_MINUN,
SPECIES_VOLBEAT,
SPECIES_ILLUMISE,
SPECIES_BUDEW,
SPECIES_ROSELIA,
SPECIES_ROSERADE,
SPECIES_GULPIN,
SPECIES_SWALOT,
SPECIES_CARVANHA,
SPECIES_SHARPEDO,
SPECIES_WAILMER,
SPECIES_WAILORD,
SPECIES_NUMEL,
SPECIES_CAMERUPT,
SPECIES_TORKOAL,
SPECIES_SPOINK,
SPECIES_GRUMPIG,
SPECIES_SPINDA,
SPECIES_TRAPINCH,
SPECIES_VIBRAVA,
SPECIES_FLYGON,
SPECIES_CACNEA,
SPECIES_CACTURNE,
SPECIES_SWABLU,
SPECIES_ALTARIA,
SPECIES_ZANGOOSE,
SPECIES_SEVIPER,
SPECIES_LUNATONE,
SPECIES_SOLROCK,
SPECIES_BARBOACH,
SPECIES_WHISCASH,
SPECIES_CORPHISH,
SPECIES_CRAWDAUNT,
SPECIES_BALTOY,
SPECIES_CLAYDOL,
SPECIES_LILEEP,
SPECIES_CRADILY,
SPECIES_ANORITH,
SPECIES_ARMALDO,
SPECIES_FEEBAS,
SPECIES_MILOTIC,
SPECIES_CASTFORM_NORMAL,
SPECIES_KECLEON,
SPECIES_SHUPPET,
SPECIES_BANETTE,
SPECIES_DUSKULL,
SPECIES_DUSCLOPS,
SPECIES_DUSKNOIR,
SPECIES_TROPIUS,
SPECIES_CHINGLING,
SPECIES_CHIMECHO,
SPECIES_ABSOL,
SPECIES_SNORUNT,
SPECIES_GLALIE,
SPECIES_FROSLASS,
SPECIES_SPHEAL,
SPECIES_SEALEO,
SPECIES_WALREIN,
SPECIES_CLAMPERL,
SPECIES_HUNTAIL,
SPECIES_GOREBYSS,
SPECIES_RELICANTH,
SPECIES_LUVDISC,
SPECIES_BAGON,
SPECIES_SHELGON,
SPECIES_SALAMENCE,
SPECIES_BELDUM,
SPECIES_METANG,
SPECIES_METAGROSS,
SPECIES_REGIROCK,
SPECIES_REGICE,
SPECIES_REGISTEEL,
SPECIES_LATIAS,
SPECIES_LATIOS,
SPECIES_KYOGRE,
SPECIES_GROUDON,
SPECIES_RAYQUAZA,
SPECIES_JIRACHI,
SPECIES_DEOXYS_NORMAL,
SPECIES_DEOXYS_ATTACK,
SPECIES_DEOXYS_DEFENSE,
SPECIES_DEOXYS_SPEED,
SPECIES_TURTWIG,
SPECIES_GROTLE,
SPECIES_TORTERRA,
SPECIES_CHIMCHAR,
SPECIES_MONFERNO,
SPECIES_INFERNAPE,
SPECIES_PIPLUP,
SPECIES_EMPOLEON,
SPECIES_STARLY,
SPECIES_STARAVIA,
SPECIES_STARAPTOR,
SPECIES_BIDOOF,
SPECIES_BIBAREL,
SPECIES_KRICKETOT,
SPECIES_KRICKETUNE,
SPECIES_SHINX,
SPECIES_LUXIO,
SPECIES_LUXRAY,
SPECIES_CRANIDOS,
SPECIES_RAMPARDOS,
SPECIES_SHIELDON,
SPECIES_BASTIODON,
SPECIES_BURMY_PLANT_CLOAK,
SPECIES_BURMY_SANDY_CLOAK,
SPECIES_BURMY_TRASH_CLOAK,
SPECIES_WORMADAM_PLANT_CLOAK,
SPECIES_WORMADAM_SANDY_CLOAK,
SPECIES_WORMADAM_TRASH_CLOAK,
SPECIES_MOTHIM_PLANT_CLOAK,
SPECIES_MOTHIM_SANDY_CLOAK,
SPECIES_MOTHIM_TRASH_CLOAK,
SPECIES_COMBEE,
SPECIES_VESPIQUEN,
SPECIES_PACHIRISU,
SPECIES_BUIZEL,
SPECIES_FLOATZEL,
SPECIES_CHERUBI,
SPECIES_CHERRIM_SUNSHINE,
SPECIES_SHELLOS_WEST_SEA,
SPECIES_SHELLOS_EAST_SEA,
SPECIES_GASTRODON_WEST_SEA,
SPECIES_GASTRODON_EAST_SEA,
SPECIES_DRIFLOON,
SPECIES_DRIFBLIM,
SPECIES_BUNEARY,
SPECIES_LOPUNNY,
SPECIES_GLAMEOW,
SPECIES_PURUGLY,
SPECIES_STUNKY,
SPECIES_SKUNTANK,
SPECIES_BRONZOR,
SPECIES_BRONZONG,
SPECIES_CHATOT,
SPECIES_SPIRITOMB,
SPECIES_GIBLE,
SPECIES_GABITE,
SPECIES_GARCHOMP,
SPECIES_RIOLU,
SPECIES_LUCARIO,
SPECIES_HIPPOPOTAS,
SPECIES_HIPPOWDON,
SPECIES_SKORUPI,
SPECIES_DRAPION,
SPECIES_CROAGUNK,
SPECIES_TOXICROAK,
SPECIES_CARNIVINE,
SPECIES_FINNEON,
SPECIES_LUMINEON,
SPECIES_SNOVER,
SPECIES_ABOMASNOW,
SPECIES_ROTOM,
SPECIES_ROTOM_HEAT,
SPECIES_ROTOM_WASH,
SPECIES_ROTOM_FROST,
SPECIES_ROTOM_FAN,
SPECIES_ROTOM_MOW,
SPECIES_UXIE,
SPECIES_MESPRIT,
SPECIES_AZELF,
SPECIES_DIALGA,
SPECIES_PALKIA,
SPECIES_HEATRAN,
SPECIES_REGIGIGAS,
SPECIES_GIRATINA_ALTERED,
SPECIES_CRESSELIA,
SPECIES_PHIONE,
SPECIES_MANAPHY,
SPECIES_DARKRAI,
SPECIES_SHAYMIN_LAND,
SPECIES_SHAYMIN_SKY,
SPECIES_ARCEUS_NORMAL,
SPECIES_VICTINI,
SPECIES_SNIVY,
SPECIES_SERVINE,
SPECIES_SERPERIOR,
SPECIES_TEPIG,
SPECIES_PIGNITE,
SPECIES_EMBOAR,
SPECIES_OSHAWOTT,
SPECIES_DEWOTT,
SPECIES_SAMUROTT,
SPECIES_SAMUROTT_HISUIAN,
SPECIES_PATRAT,
SPECIES_WATCHOG,
SPECIES_LILLIPUP,
SPECIES_HERDIER,
SPECIES_STOUTLAND,
SPECIES_PURRLOIN,
SPECIES_LIEPARD,
SPECIES_PANSAGE,
SPECIES_SIMISAGE,
SPECIES_PANSEAR,
SPECIES_SIMISEAR,
SPECIES_PANPOUR,
SPECIES_SIMIPOUR,
SPECIES_MUNNA,
SPECIES_MUSHARNA,
SPECIES_PIDOVE,
SPECIES_TRANQUILL,
SPECIES_UNFEZANT,
SPECIES_BLITZLE,
SPECIES_ZEBSTRIKA,
SPECIES_ROGGENROLA,
SPECIES_BOLDORE,
SPECIES_GIGALITH,
SPECIES_WOOBAT,
SPECIES_SWOOBAT,
SPECIES_DRILBUR,
SPECIES_EXCADRILL,
SPECIES_AUDINO,
SPECIES_TIMBURR,
SPECIES_GURDURR,
SPECIES_CONKELDURR,
SPECIES_TYMPOLE,
SPECIES_PALPITOAD,
SPECIES_SEISMITOAD,
SPECIES_THROH,
SPECIES_SAWK,
SPECIES_SEWADDLE,
SPECIES_SWADLOON,
SPECIES_LEAVANNY,
SPECIES_VENIPEDE,
SPECIES_WHIRLIPEDE,
SPECIES_SCOLIPEDE,
SPECIES_COTTONEE,
SPECIES_WHIMSICOTT,
SPECIES_PETILIL,
SPECIES_LILLIGANT,
SPECIES_LILLIGANT_HISUIAN,
SPECIES_BASCULIN_RED_STRIPED,
SPECIES_BASCULIN_BLUE_STRIPED,
SPECIES_BASCULIN_WHITE_STRIPED,
SPECIES_BASCULEGION_MALE,
SPECIES_BASCULEGION_FEMALE,
SPECIES_SANDILE,
SPECIES_KROKOROK,
SPECIES_KROOKODILE,
SPECIES_DARUMAKA,
SPECIES_DARMANITAN_STANDARD_MODE,
SPECIES_DARUMAKA_GALARIAN,
SPECIES_DARMANITAN_GALARIAN_STANDARD_MODE,
SPECIES_MARACTUS,
SPECIES_DWEBBLE,
SPECIES_CRUSTLE,
SPECIES_SCRAGGY,
SPECIES_SCRAFTY,
SPECIES_SIGILYPH,
SPECIES_YAMASK,
SPECIES_COFAGRIGUS,
SPECIES_YAMASK_GALARIAN,
SPECIES_RUNERIGUS,
SPECIES_TIRTOUGA,
SPECIES_CARRACOSTA,
SPECIES_ARCHEN,
SPECIES_ARCHEOPS,
SPECIES_TRUBBISH,
SPECIES_GARBODOR,
SPECIES_ZORUA,
SPECIES_ZOROARK,
SPECIES_ZORUA_HISUIAN,
SPECIES_ZOROARK_HISUIAN,
SPECIES_MINCCINO,
SPECIES_CINCCINO,
SPECIES_GOTHITA,
SPECIES_GOTHORITA,
SPECIES_GOTHITELLE,
SPECIES_SOLOSIS,
SPECIES_DUOSION,
SPECIES_REUNICLUS,
SPECIES_DUCKLETT,
SPECIES_SWANNA,
SPECIES_VANILLITE,
SPECIES_VANILLISH,
SPECIES_VANILLUXE,
SPECIES_DEERLING_SUMMER,
SPECIES_SAWSBUCK_SPRING,
SPECIES_EMOLGA,
SPECIES_KARRABLAST,
SPECIES_ESCAVALIER,
SPECIES_FOONGUS,
SPECIES_AMOONGUSS,
SPECIES_FRILLISH,
SPECIES_JELLICENT,
SPECIES_ALOMOMOLA,
SPECIES_JOLTIK,
SPECIES_GALVANTULA,
SPECIES_FERROSEED,
SPECIES_FERROTHORN,
SPECIES_KLINK,
SPECIES_KLANG,
SPECIES_KLINKLANG,
SPECIES_TYNAMO,
SPECIES_EELEKTRIK,
SPECIES_EELEKTROSS,
SPECIES_ELGYEM,
SPECIES_BEHEEYEM,
SPECIES_LITWICK,
SPECIES_LAMPENT,
SPECIES_CHANDELURE,
SPECIES_AXEW,
SPECIES_FRAXURE,
SPECIES_HAXORUS,
SPECIES_CUBCHOO,
SPECIES_BEARTIC,
SPECIES_CRYOGONAL,
SPECIES_SHELMET,
SPECIES_ACCELGOR,
SPECIES_STUNFISK,
SPECIES_STUNFISK_GALARIAN,
SPECIES_MIENFOO,
SPECIES_MIENSHAO,
SPECIES_DRUDDIGON,
SPECIES_GOLETT,
SPECIES_GOLURK,
SPECIES_PAWNIARD,
SPECIES_BISHARP,
SPECIES_KINGAMBIT,
SPECIES_BOUFFALANT,
SPECIES_RUFFLET,
SPECIES_BRAVIARY,
SPECIES_BRAVIARY_HISUIAN,
SPECIES_VULLABY,
SPECIES_MANDIBUZZ,
SPECIES_HEATMOR,
SPECIES_DURANT,
SPECIES_DEINO,
SPECIES_ZWEILOUS,
SPECIES_HYDREIGON,
SPECIES_LARVESTA,
SPECIES_VOLCARONA,
SPECIES_COBALION,
SPECIES_TERRAKION,
SPECIES_VIRIZION,
SPECIES_TORNADUS_INCARNATE,
SPECIES_TORNADUS_THERIAN,
SPECIES_THUNDURUS_INCARNATE,
SPECIES_THUNDURUS_THERIAN,
SPECIES_RESHIRAM,
SPECIES_ZEKROM,
SPECIES_LANDORUS_INCARNATE,
SPECIES_LANDORUS_THERIAN,
SPECIES_KYUREM,
SPECIES_KYUREM_WHITE,
SPECIES_KYUREM_BLACK,
SPECIES_KELDEO_ORDINARY,
SPECIES_KELDEO_RESOLUTE,
SPECIES_MELOETTA_ARIA,
SPECIES_MELOETTA_PIROUETTE,
SPECIES_GENESECT,
SPECIES_CHESPIN,
SPECIES_QUILLADIN,
SPECIES_CHESNAUGHT,
SPECIES_FENNEKIN,
SPECIES_BRAIXEN,
SPECIES_DELPHOX,
SPECIES_FROAKIE,
SPECIES_FROGADIER,
SPECIES_GRENINJA,
SPECIES_BUNNELBY,
SPECIES_DIGGERSBY,
SPECIES_FLETCHLING,
SPECIES_FLETCHINDER,
SPECIES_TALONFLAME,
SPECIES_SCATTERBUG_POKE_BALL,
SPECIES_SPEWPA_POKE_BALL,
SPECIES_VIVILLON_POKE_BALL,
SPECIES_LITLEO,
SPECIES_PYROAR,
SPECIES_FLABEBE_WHITE_FLOWER,
SPECIES_FLOETTE_WHITE_FLOWER,
SPECIES_FLOETTE_ETERNAL_FLOWER,
SPECIES_FLORGES_WHITE_FLOWER,
SPECIES_SKIDDO,
SPECIES_GOGOAT,
SPECIES_PANCHAM,
SPECIES_PANGORO,
SPECIES_FURFROU_NATURAL,
SPECIES_ESPURR,
SPECIES_MEOWSTIC_MALE,
SPECIES_MEOWSTIC_FEMALE,
SPECIES_HONEDGE,
SPECIES_DOUBLADE,
SPECIES_AEGISLASH_SHIELD,
SPECIES_AEGISLASH_BLADE,
SPECIES_SPRITZEE,
SPECIES_AROMATISSE,
SPECIES_SWIRLIX,
SPECIES_SLURPUFF,
SPECIES_INKAY,
SPECIES_MALAMAR,
SPECIES_BINACLE,
SPECIES_BARBARACLE,
SPECIES_SKRELP,
SPECIES_DRAGALGE,
SPECIES_CLAUNCHER,
SPECIES_CLAWITZER,
SPECIES_HELIOPTILE,
SPECIES_HELIOLISK,
SPECIES_TYRUNT,
SPECIES_TYRANTRUM,
SPECIES_AMAURA,
SPECIES_AURORUS,
SPECIES_HAWLUCHA,
SPECIES_DEDENNE,
SPECIES_CARBINK,
SPECIES_GOOMY,
SPECIES_SLIGGOO,
SPECIES_GOODRA,
SPECIES_SLIGGOO_HISUIAN,
SPECIES_GOODRA_HISUIAN,
SPECIES_KLEFKI,
SPECIES_PHANTUMP,
SPECIES_TREVENANT,
SPECIES_PUMPKABOO_SMALL,
SPECIES_PUMPKABOO_SUPER,
SPECIES_GOURGEIST_SMALL,
SPECIES_GOURGEIST_SUPER,
SPECIES_BERGMITE,
SPECIES_AVALUGG,
SPECIES_AVALUGG_HISUIAN,
SPECIES_NOIBAT,
SPECIES_NOIVERN,
SPECIES_XERNEAS_NEUTRAL,
SPECIES_XERNEAS_ACTIVE,
SPECIES_YVELTAL,
SPECIES_ZYGARDE_50_AURA_BREAK,
SPECIES_ZYGARDE_50_POWER_CONSTRUCT,
SPECIES_ZYGARDE_10_AURA_BREAK,
SPECIES_ZYGARDE_10_POWER_CONSTRUCT,
SPECIES_ZYGARDE_COMPLETE,
SPECIES_DIANCIE,
SPECIES_HOOPA_CONFINED,
SPECIES_HOOPA_UNBOUND,
SPECIES_VOLCANION,
SPECIES_ROWLET,
SPECIES_DARTRIX,
SPECIES_DECIDUEYE,
SPECIES_DECIDUEYE_HISUIAN,
SPECIES_LITTEN,
SPECIES_TORRACAT,
SPECIES_INCINEROAR,
SPECIES_POPPLIO,
SPECIES_BRIONNE,
SPECIES_PRIMARINA,
SPECIES_PIKIPEK,
SPECIES_TRUMBEAK,
SPECIES_TOUCANNON,
SPECIES_YUNGOOS,
SPECIES_GUMSHOOS,
SPECIES_GUMSHOOS_TOTEM,
SPECIES_GRUBBIN,
SPECIES_CHARJABUG,
SPECIES_VIKAVOLT,
SPECIES_VIKAVOLT_TOTEM,
SPECIES_CRABRAWLER,
SPECIES_CRABOMINABLE,
SPECIES_ORICORIO_BAILE,
SPECIES_ORICORIO_POM_POM,
SPECIES_ORICORIO_PAU,
SPECIES_ORICORIO_SENSU,
SPECIES_CUTIEFLY,
SPECIES_RIBOMBEE,
SPECIES_RIBOMBEE_TOTEM,
SPECIES_ROCKRUFF,
SPECIES_ROCKRUFF_OWN_TEMPO,
SPECIES_LYCANROC_MIDDAY,
SPECIES_LYCANROC_MIDNIGHT,
SPECIES_LYCANROC_DUSK,
SPECIES_WISHIWASHI_SOLO,
SPECIES_WISHIWASHI_SCHOOL,
SPECIES_MAREANIE,
SPECIES_TOXAPEX,
SPECIES_MUDBRAY,
SPECIES_MUDSDALE,
SPECIES_DEWPIDER,
SPECIES_ARAQUANID,
SPECIES_ARAQUANID_TOTEM,
SPECIES_FOMANTIS,
SPECIES_LURANTIS,
SPECIES_LURANTIS_TOTEM,
SPECIES_MORELULL,
SPECIES_SHIINOTIC,
SPECIES_SALANDIT,
SPECIES_SALAZZLE,
SPECIES_SALAZZLE_TOTEM,
SPECIES_STUFFUL,
SPECIES_BEWEAR,
SPECIES_BOUNSWEET,
SPECIES_STEENEE,
SPECIES_TSAREENA,
SPECIES_COMFEY,
SPECIES_ORANGURU,
SPECIES_PASSIMIAN,
SPECIES_WIMPOD,
SPECIES_GOLISOPOD,
SPECIES_SANDYGAST,
SPECIES_PALOSSAND,
SPECIES_PYUKUMUKU,
SPECIES_TYPE_NULL,
SPECIES_SILVALLY_NORMAL,
SPECIES_MINIOR_METEOR_VIOLET,
SPECIES_MINIOR_CORE_VIOLET,
SPECIES_KOMALA,
SPECIES_TURTONATOR,
SPECIES_TOGEDEMARU,
SPECIES_TOGEDEMARU_TOTEM,
SPECIES_MIMIKYU_DISGUISED,
SPECIES_MIMIKYU_TOTEM_DISGUISED,
SPECIES_BRUXISH,
SPECIES_DRAMPA,
SPECIES_DHELMISE,
SPECIES_JANGMO_O,
SPECIES_HAKAMO_O,
SPECIES_KOMMO_O,
SPECIES_KOMMO_O_TOTEM,
SPECIES_TAPU_KOKO,
SPECIES_TAPU_LELE,
SPECIES_TAPU_BULU,
SPECIES_TAPU_FINI,
SPECIES_COSMOG,
SPECIES_COSMOEM,
SPECIES_SOLGALEO,
SPECIES_LUNALA,
SPECIES_NIHILEGO,
SPECIES_BUZZWOLE,
SPECIES_PHEROMOSA,
SPECIES_XURKITREE,
SPECIES_CELESTEELA,
SPECIES_KARTANA,
SPECIES_GUZZLORD,
SPECIES_NECROZMA,
SPECIES_NECROZMA_DUSK_MANE,
SPECIES_NECROZMA_DAWN_WINGS,
SPECIES_MAGEARNA,
SPECIES_MAGEARNA_ORIGINAL_COLOR,
SPECIES_MARSHADOW,
SPECIES_POIPOLE,
SPECIES_NAGANADEL,
SPECIES_STAKATAKA,
SPECIES_BLACEPHALON,
SPECIES_ZERAORA,
SPECIES_MELTAN,
SPECIES_MELMETAL,
SPECIES_GROOKEY,
SPECIES_THWACKEY,
SPECIES_RILLABOOM,
SPECIES_SCORBUNNY,
SPECIES_RABOOT,
SPECIES_CINDERACE,
SPECIES_SOBBLE,
SPECIES_DRIZZILE,
SPECIES_INTELEON,
SPECIES_SKWOVET,
SPECIES_GREEDENT,
SPECIES_ROOKIDEE,
SPECIES_CORVISQUIRE,
SPECIES_CORVIKNIGHT,
SPECIES_BLIPBUG,
SPECIES_DOTTLER,
SPECIES_ORBEETLE,
SPECIES_NICKIT,
SPECIES_THIEVUL,
SPECIES_GOSSIFLEUR,
SPECIES_ELDEGOSS,
SPECIES_WOOLOO,
SPECIES_DUBWOOL,
SPECIES_CHEWTLE,
SPECIES_DREDNAW,
SPECIES_YAMPER,
SPECIES_BOLTUND,
SPECIES_ROLYCOLY,
SPECIES_CARKOL,
SPECIES_COALOSSAL,
SPECIES_APPLIN,
SPECIES_FLAPPLE,
SPECIES_APPLETUN,
SPECIES_DIPPLIN,
SPECIES_HYDRAPPLE,
SPECIES_SILICOBRA,
SPECIES_SANDACONDA,
SPECIES_CRAMORANT,
SPECIES_ARROKUDA,
SPECIES_BARRASKEWDA,
SPECIES_TOXEL,
SPECIES_TOXTRICITY_AMPED,
SPECIES_TOXTRICITY_LOW_KEY,
SPECIES_SIZZLIPEDE,
SPECIES_CENTISKORCH,
SPECIES_CLOBBOPUS,
SPECIES_GRAPPLOCT,
SPECIES_SINISTEA_PHONY,
SPECIES_SINISTEA_ANTIQUE,
SPECIES_POLTEAGEIST_PHONY,
SPECIES_POLTEAGEIST_ANTIQUE,
SPECIES_HATENNA,
SPECIES_HATTREM,
SPECIES_HATTERENE,
SPECIES_IMPIDIMP,
SPECIES_MORGREM,
SPECIES_GRIMMSNARL,
SPECIES_MILCERY,
SPECIES_ALCREMIE_RIBBON_RAINBOW_SWIRL,
SPECIES_FALINKS,
SPECIES_PINCURCHIN,
SPECIES_SNOM,
SPECIES_FROSMOTH,
SPECIES_STONJOURNER,
SPECIES_EISCUE_ICE_FACE,
SPECIES_INDEEDEE_MALE,
SPECIES_INDEEDEE_FEMALE,
SPECIES_MORPEKO_FULL_BELLY,
SPECIES_CUFANT,
SPECIES_COPPERAJAH,
SPECIES_DRACOZOLT,
SPECIES_ARCTOZOLT,
SPECIES_DRACOVISH,
SPECIES_ARCTOVISH,
SPECIES_DURALUDON,
SPECIES_ARCHALUDON,
SPECIES_DREEPY,
SPECIES_DRAKLOAK,
SPECIES_DRAGAPULT,
SPECIES_ZACIAN_HERO_OF_MANY_BATTLES,
SPECIES_ZACIAN_CROWNED_SWORD,
SPECIES_ZAMAZENTA_HERO_OF_MANY_BATTLES,
SPECIES_ZAMAZENTA_CROWNED_SHIELD,
SPECIES_ETERNATUS,
SPECIES_KUBFU,
SPECIES_URSHIFU_SINGLE_STRIKE_STYLE,
SPECIES_URSHIFU_RAPID_STRIKE_STYLE,
SPECIES_ZARUDE,
SPECIES_ZARUDE_DADA,
SPECIES_REGIELEKI,
SPECIES_REGIDRAGO,
SPECIES_GLASTRIER,
SPECIES_SPECTRIER,
SPECIES_CALYREX,
SPECIES_CALYREX_ICE_RIDER,
SPECIES_CALYREX_SHADOW_RIDER,
SPECIES_ENAMORUS_INCARNATE,
SPECIES_ENAMORUS_THERIAN,
SPECIES_SPRIGATITO,
SPECIES_FLORAGATO,
SPECIES_MEOWSCARADA,
SPECIES_FUECOCO,
SPECIES_CROCALOR,
SPECIES_SKELEDIRGE,
SPECIES_QUAXLY,
SPECIES_QUAXWELL,
SPECIES_QUAQUAVAL,
SPECIES_LECHONK,
SPECIES_OINKOLOGNE_MALE,
SPECIES_OINKOLOGNE_FEMALE,
SPECIES_TAROUNTULA,
SPECIES_SPIDOPS,
SPECIES_NYMBLE,
SPECIES_LOKIX,
SPECIES_PAWMI,
SPECIES_PAWMO,
SPECIES_PAWMOT,
SPECIES_TANDEMAUS,
SPECIES_MAUSHOLD_FAMILY_OF_THREE,
SPECIES_MAUSHOLD_FAMILY_OF_FOUR,
SPECIES_FIDOUGH,
SPECIES_DACHSBUN,
SPECIES_SMOLIV,
SPECIES_DOLLIV,
SPECIES_ARBOLIVA,
SPECIES_SQUAWKABILLY_YELLOW_PLUMAGE,
SPECIES_NACLI,
SPECIES_NACLSTACK,
SPECIES_GARGANACL,
SPECIES_CHARCADET,
SPECIES_ARMAROUGE,
SPECIES_CERULEDGE,
SPECIES_TADBULB,
SPECIES_BELLIBOLT,
SPECIES_WATTREL,
SPECIES_KILOWATTREL,
SPECIES_MASCHIFF,
SPECIES_MABOSSTIFF,
SPECIES_SHROODLE,
SPECIES_GRAFAIAI,
SPECIES_BRAMBLIN,
SPECIES_BRAMBLEGHAST,
SPECIES_TOEDSCOOL,
SPECIES_TOEDSCRUEL,
SPECIES_KLAWF,
SPECIES_CAPSAKID,
SPECIES_SCOVILLAIN,
SPECIES_RELLOR,
SPECIES_RABSCA,
SPECIES_FLITTLE,
SPECIES_ESPATHRA,
SPECIES_TINKATINK,
SPECIES_TINKATUFF,
SPECIES_TINKATON,
SPECIES_WIGLETT,
SPECIES_WUGTRIO,
SPECIES_BOMBIRDIER,
SPECIES_FINIZEN,
SPECIES_PALAFIN_ZERO,
SPECIES_VAROOM,
SPECIES_REVAVROOM,
SPECIES_CYCLIZAR,
SPECIES_ORTHWORM,
SPECIES_GLIMMET,
SPECIES_GLIMMORA,
SPECIES_GREAVARD,
SPECIES_HOUNDSTONE,
SPECIES_FLAMIGO,
SPECIES_CETODDLE,
SPECIES_CETITAN,
SPECIES_VELUZA,
SPECIES_DONDOZO,
SPECIES_TATSUGIRI_CURLY,
SPECIES_GREAT_TUSK,
SPECIES_SCREAM_TAIL,
SPECIES_BRUTE_BONNET,
SPECIES_FLUTTER_MANE,
SPECIES_SLITHER_WING,
SPECIES_SANDY_SHOCKS,
SPECIES_IRON_TREADS,
SPECIES_IRON_BUNDLE,
SPECIES_IRON_HANDS,
SPECIES_IRON_JUGULIS,
SPECIES_IRON_MOTH,
SPECIES_IRON_THORNS,
SPECIES_FRIGIBAX,
SPECIES_ARCTIBAX,
SPECIES_BAXCALIBUR,
SPECIES_GIMMIGHOUL_CHEST,
SPECIES_GIMMIGHOUL_ROAMING,
SPECIES_GHOLDENGO,
SPECIES_WO_CHIEN,
SPECIES_CHIEN_PAO,
SPECIES_TING_LU,
SPECIES_CHI_YU,
SPECIES_ROARING_MOON,
SPECIES_IRON_VALIANT,
SPECIES_KORAIDON,
SPECIES_MIRAIDON,
SPECIES_WALKING_WAKE,
SPECIES_IRON_LEAVES,
SPECIES_POLTCHAGEIST_COUNTERFEIT,
SPECIES_POLTCHAGEIST_ARTISAN,
SPECIES_SINISTCHA_UNREMARKABLE,
SPECIES_SINISTCHA_MASTERPIECE,
SPECIES_OKIDOGI,
SPECIES_MUNKIDORI,
SPECIES_FEZANDIPITI,
SPECIES_OGERPON_TEAL_MASK,
SPECIES_GOUGING_FIRE,
SPECIES_RAGING_BOLT,
SPECIES_IRON_BOULDER,
SPECIES_IRON_CROWN,
SPECIES_TERAPAGOS_NORMAL,
SPECIES_TERAPAGOS_TERASTAL,
SPECIES_TERAPAGOS_STELLAR,
SPECIES_PECHARUNT,
};

static void CreateWildMon(u16 species, u8 level)
{
    bool32 checkCuteCharm;

    ZeroEnemyPartyMons();
    checkCuteCharm = OW_CUTE_CHARM < GEN_9;

    if (gSaveBlock1Ptr->location.mapGroup == MAP_GROUP(SAFARI_ZONE_SOUTH)
    && gSaveBlock1Ptr->location.mapNum == MAP_NUM(SAFARI_ZONE_SOUTH))
    {
        species = gRandomMonListArray[Random() % 1191];
     }

    switch (gSpeciesInfo[species].genderRatio)
    {
    case MON_MALE:
    case MON_FEMALE:
    case MON_GENDERLESS:
        checkCuteCharm = FALSE;
        break;
    }

    if (checkCuteCharm
        && !GetMonData(&gPlayerParty[0], MON_DATA_SANITY_IS_EGG)
        && GetMonAbility(&gPlayerParty[0]) == ABILITY_CUTE_CHARM
        && Random() % 3 != 0)
    {
        u16 leadingMonSpecies = GetMonData(&gPlayerParty[0], MON_DATA_SPECIES);
        u32 leadingMonPersonality = GetMonData(&gPlayerParty[0], MON_DATA_PERSONALITY);
        u8 gender = GetGenderFromSpeciesAndPersonality(leadingMonSpecies, leadingMonPersonality);

        // misses mon is genderless check, although no genderless mon can have cute charm as ability
        if (gender == MON_FEMALE)
            gender = MON_MALE;
        else
            gender = MON_FEMALE;

        CreateMonWithGenderNatureLetter(&gEnemyParty[0], species, level, USE_RANDOM_IVS, gender, PickWildMonNature(), 0);
        return;
    }

    CreateMonWithNature(&gEnemyParty[0], species, level, USE_RANDOM_IVS, PickWildMonNature());
}
#ifdef BUGFIX
#define TRY_GET_ABILITY_INFLUENCED_WILD_MON_INDEX(wildPokemon, type, ability, ptr, count) TryGetAbilityInfluencedWildMonIndex(wildPokemon, type, ability, ptr, count)
#else
#define TRY_GET_ABILITY_INFLUENCED_WILD_MON_INDEX(wildPokemon, type, ability, ptr, count) TryGetAbilityInfluencedWildMonIndex(wildPokemon, type, ability, ptr)
#endif

static bool8 TryGenerateWildMon(const struct WildPokemonInfo *wildMonInfo, u8 area, u8 flags)
{
    u8 wildMonIndex = 0;
    u8 level;

    switch (area)
    {
    case WILD_AREA_LAND:
        if (OW_MAGNET_PULL < GEN_9 && TRY_GET_ABILITY_INFLUENCED_WILD_MON_INDEX(wildMonInfo->wildPokemon, TYPE_STEEL, ABILITY_MAGNET_PULL, &wildMonIndex, LAND_WILD_COUNT))
            break;
        if (OW_STATIC < GEN_9 && TRY_GET_ABILITY_INFLUENCED_WILD_MON_INDEX(wildMonInfo->wildPokemon, TYPE_ELECTRIC, ABILITY_STATIC, &wildMonIndex, LAND_WILD_COUNT))
            break;
        if (OW_LIGHTNING_ROD == GEN_8 && TRY_GET_ABILITY_INFLUENCED_WILD_MON_INDEX(wildMonInfo->wildPokemon, TYPE_ELECTRIC, ABILITY_LIGHTNING_ROD, &wildMonIndex, LAND_WILD_COUNT))
            break;
        if (OW_FLASH_FIRE == GEN_8 && TRY_GET_ABILITY_INFLUENCED_WILD_MON_INDEX(wildMonInfo->wildPokemon, TYPE_FIRE, ABILITY_FLASH_FIRE, &wildMonIndex, LAND_WILD_COUNT))
            break;
        if (OW_HARVEST == GEN_8 && TRY_GET_ABILITY_INFLUENCED_WILD_MON_INDEX(wildMonInfo->wildPokemon, TYPE_GRASS, ABILITY_HARVEST, &wildMonIndex, LAND_WILD_COUNT))
            break;
        if (OW_STORM_DRAIN == GEN_8 && TRY_GET_ABILITY_INFLUENCED_WILD_MON_INDEX(wildMonInfo->wildPokemon, TYPE_WATER, ABILITY_STORM_DRAIN, &wildMonIndex, LAND_WILD_COUNT))
            break;

        wildMonIndex = ChooseWildMonIndex_Land();
        break;
    case WILD_AREA_WATER:
        if (OW_MAGNET_PULL < GEN_9 && TRY_GET_ABILITY_INFLUENCED_WILD_MON_INDEX(wildMonInfo->wildPokemon, TYPE_STEEL, ABILITY_MAGNET_PULL, &wildMonIndex, WATER_WILD_COUNT))
            break;
        if (OW_STATIC < GEN_9 && TRY_GET_ABILITY_INFLUENCED_WILD_MON_INDEX(wildMonInfo->wildPokemon, TYPE_ELECTRIC, ABILITY_STATIC, &wildMonIndex, WATER_WILD_COUNT))
            break;
        if (OW_LIGHTNING_ROD == GEN_8 && TRY_GET_ABILITY_INFLUENCED_WILD_MON_INDEX(wildMonInfo->wildPokemon, TYPE_ELECTRIC, ABILITY_LIGHTNING_ROD, &wildMonIndex, WATER_WILD_COUNT))
            break;
        if (OW_FLASH_FIRE == GEN_8 && TRY_GET_ABILITY_INFLUENCED_WILD_MON_INDEX(wildMonInfo->wildPokemon, TYPE_FIRE, ABILITY_FLASH_FIRE, &wildMonIndex, WATER_WILD_COUNT))
            break;
        if (OW_HARVEST == GEN_8 && TRY_GET_ABILITY_INFLUENCED_WILD_MON_INDEX(wildMonInfo->wildPokemon, TYPE_GRASS, ABILITY_HARVEST, &wildMonIndex, WATER_WILD_COUNT))
            break;
        if (OW_STORM_DRAIN == GEN_8 && TRY_GET_ABILITY_INFLUENCED_WILD_MON_INDEX(wildMonInfo->wildPokemon, TYPE_WATER, ABILITY_STORM_DRAIN, &wildMonIndex, WATER_WILD_COUNT))
            break;

        wildMonIndex = ChooseWildMonIndex_WaterRock();
        break;
    case WILD_AREA_ROCKS:
        wildMonIndex = ChooseWildMonIndex_WaterRock();
        break;
    }

    level = ChooseWildMonLevel(wildMonInfo->wildPokemon, wildMonIndex, area);
    if (flags & WILD_CHECK_REPEL && !IsWildLevelAllowedByRepel(level))
        return FALSE;
    if (gMapHeader.mapLayoutId != LAYOUT_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS && flags & WILD_CHECK_KEEN_EYE && !IsAbilityAllowingEncounter(level))
        return FALSE;

    CreateWildMon(wildMonInfo->wildPokemon[wildMonIndex].species, level);
    return TRUE;
}

static u16 GenerateFishingWildMon(const struct WildPokemonInfo *wildMonInfo, u8 rod)
{
    u8 wildMonIndex = ChooseWildMonIndex_Fishing(rod);
    u8 level = ChooseWildMonLevel(wildMonInfo->wildPokemon, wildMonIndex, WILD_AREA_FISHING);

    CreateWildMon(wildMonInfo->wildPokemon[wildMonIndex].species, level);
    return wildMonInfo->wildPokemon[wildMonIndex].species;
}

static bool8 SetUpMassOutbreakEncounter(u8 flags)
{
    u16 i;

    if (flags & WILD_CHECK_REPEL && !IsWildLevelAllowedByRepel(gSaveBlock1Ptr->outbreakPokemonLevel))
        return FALSE;

    CreateWildMon(gSaveBlock1Ptr->outbreakPokemonSpecies, gSaveBlock1Ptr->outbreakPokemonLevel);
    for (i = 0; i < MAX_MON_MOVES; i++)
        SetMonMoveSlot(&gEnemyParty[0], gSaveBlock1Ptr->outbreakPokemonMoves[i], i);

    return TRUE;
}

static bool8 DoMassOutbreakEncounterTest(void)
{
    if (gSaveBlock1Ptr->outbreakPokemonSpecies != SPECIES_NONE
     && gSaveBlock1Ptr->location.mapNum == gSaveBlock1Ptr->outbreakLocationMapNum
     && gSaveBlock1Ptr->location.mapGroup == gSaveBlock1Ptr->outbreakLocationMapGroup)
    {
        if (Random() % 100 < gSaveBlock1Ptr->outbreakPokemonProbability)
            return TRUE;
    }
    return FALSE;
}

static bool8 EncounterOddsCheck(u16 encounterRate)
{
    if (Random() % MAX_ENCOUNTER_RATE < encounterRate)
        return TRUE;
    else
        return FALSE;
}

// Returns true if it will try to create a wild encounter.
static bool8 WildEncounterCheck(u32 encounterRate, bool8 ignoreAbility)
{
    encounterRate *= 16;
    if (TestPlayerAvatarFlags(PLAYER_AVATAR_FLAG_MACH_BIKE | PLAYER_AVATAR_FLAG_ACRO_BIKE))
        encounterRate = encounterRate * 80 / 100;
    ApplyFluteEncounterRateMod(&encounterRate);
    ApplyCleanseTagEncounterRateMod(&encounterRate);
    if (LURE_STEP_COUNT != 0)
        encounterRate *= 2;
    if (!ignoreAbility && !GetMonData(&gPlayerParty[0], MON_DATA_SANITY_IS_EGG))
    {
        u32 ability = GetMonAbility(&gPlayerParty[0]);

        if (ability == ABILITY_STENCH && gMapHeader.mapLayoutId == LAYOUT_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR)
            encounterRate = encounterRate * 3 / 4;
        else if (ability == ABILITY_STENCH)
            encounterRate /= 2;
        else if (ability == ABILITY_ILLUMINATE && OW_ILLUMINATE < GEN_9)
            encounterRate *= 2;
        else if (ability == ABILITY_WHITE_SMOKE)
            encounterRate /= 2;
        else if (ability == ABILITY_ARENA_TRAP)
            encounterRate *= 2;
        else if (ability == ABILITY_SAND_VEIL && gSaveBlock1Ptr->weather == WEATHER_SANDSTORM)
            encounterRate /= 2;
        else if (ability == ABILITY_SNOW_CLOAK && gSaveBlock1Ptr->weather == WEATHER_SNOW)
            encounterRate /= 2;
        else if (ability == ABILITY_QUICK_FEET)
            encounterRate /= 2;
        else if (ability == ABILITY_INFILTRATOR && OW_INFILTRATOR == GEN_8)
            encounterRate /= 2;
        else if (ability == ABILITY_NO_GUARD)
            encounterRate *= 2;
    }
    if (encounterRate > MAX_ENCOUNTER_RATE)
        encounterRate = MAX_ENCOUNTER_RATE;
    return EncounterOddsCheck(encounterRate);
}

// When you first step on a different type of metatile, there's a 40% chance it
// skips the wild encounter check entirely.
static bool8 AllowWildCheckOnNewMetatile(void)
{
    if (Random() % 100 >= 60)
        return FALSE;
    else
        return TRUE;
}

static bool8 AreLegendariesInSootopolisPreventingEncounters(void)
{
    if (gSaveBlock1Ptr->location.mapGroup != MAP_GROUP(SOOTOPOLIS_CITY)
     || gSaveBlock1Ptr->location.mapNum != MAP_NUM(SOOTOPOLIS_CITY))
    {
        return FALSE;
    }

    return FlagGet(FLAG_LEGENDARIES_IN_SOOTOPOLIS);
}

bool8 StandardWildEncounter(u16 curMetatileBehavior, u16 prevMetatileBehavior)
{
    u16 headerId;
    struct Roamer *roamer;

    if (sWildEncountersDisabled == TRUE)
        return FALSE;

    headerId = GetCurrentMapWildMonHeaderId();
    if (headerId == HEADER_NONE)
    {
        if (gMapHeader.mapLayoutId == LAYOUT_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS)
        {
            headerId = GetBattlePikeWildMonHeaderId();
            if (prevMetatileBehavior != curMetatileBehavior && !AllowWildCheckOnNewMetatile())
                return FALSE;
            else if (WildEncounterCheck(gBattlePikeWildMonHeaders[headerId].landMonsInfo->encounterRate, FALSE) != TRUE)
                return FALSE;
            else if (TryGenerateWildMon(gBattlePikeWildMonHeaders[headerId].landMonsInfo, WILD_AREA_LAND, WILD_CHECK_KEEN_EYE) != TRUE)
                return FALSE;
            else if (!TryGenerateBattlePikeWildMon(TRUE))
                return FALSE;

            BattleSetup_StartBattlePikeWildBattle();
            return TRUE;
        }
        if (gMapHeader.mapLayoutId == LAYOUT_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR)
        {
            headerId = gSaveBlock2Ptr->frontier.curChallengeBattleNum;
            if (prevMetatileBehavior != curMetatileBehavior && !AllowWildCheckOnNewMetatile())
                return FALSE;
            else if (WildEncounterCheck(gBattlePyramidWildMonHeaders[headerId].landMonsInfo->encounterRate, FALSE) != TRUE)
                return FALSE;
            else if (TryGenerateWildMon(gBattlePyramidWildMonHeaders[headerId].landMonsInfo, WILD_AREA_LAND, WILD_CHECK_KEEN_EYE) != TRUE)
                return FALSE;

            GenerateBattlePyramidWildMon();
            BattleSetup_StartWildBattle();
            return TRUE;
        }
    }
    else
    {
        if (MetatileBehavior_IsLandWildEncounter(curMetatileBehavior) == TRUE)
        {
            if (gWildMonHeaders[headerId].landMonsInfo == NULL)
                return FALSE;
            else if (prevMetatileBehavior != curMetatileBehavior && !AllowWildCheckOnNewMetatile())
                return FALSE;
            else if (WildEncounterCheck(gWildMonHeaders[headerId].landMonsInfo->encounterRate, FALSE) != TRUE)
                return FALSE;

            if (TryStartRoamerEncounter() == TRUE)
            {
                roamer = &gSaveBlock1Ptr->roamer;
                if (!IsWildLevelAllowedByRepel(roamer->level))
                    return FALSE;

                BattleSetup_StartRoamerBattle();
                return TRUE;
            }
            else
            {
                if (DoMassOutbreakEncounterTest() == TRUE && SetUpMassOutbreakEncounter(WILD_CHECK_REPEL | WILD_CHECK_KEEN_EYE) == TRUE)
                {
                    BattleSetup_StartWildBattle();
                    return TRUE;
                }

                // try a regular wild land encounter
                if (TryGenerateWildMon(gWildMonHeaders[headerId].landMonsInfo, WILD_AREA_LAND, WILD_CHECK_REPEL | WILD_CHECK_KEEN_EYE) == TRUE)
                {
                    if (TryDoDoubleWildBattle())
                    {
                        struct Pokemon mon1 = gEnemyParty[0];
                        TryGenerateWildMon(gWildMonHeaders[headerId].landMonsInfo, WILD_AREA_LAND, WILD_CHECK_KEEN_EYE);
                        gEnemyParty[1] = mon1;
                        BattleSetup_StartDoubleWildBattle();
                    }
                    else
                    {
                        BattleSetup_StartWildBattle();
                    }
                    return TRUE;
                }

                return FALSE;
            }
        }
        else if (MetatileBehavior_IsWaterWildEncounter(curMetatileBehavior) == TRUE
                 || (TestPlayerAvatarFlags(PLAYER_AVATAR_FLAG_SURFING) && MetatileBehavior_IsBridgeOverWater(curMetatileBehavior) == TRUE))
        {
            if (AreLegendariesInSootopolisPreventingEncounters() == TRUE)
                return FALSE;
            else if (gWildMonHeaders[headerId].waterMonsInfo == NULL)
                return FALSE;
            else if (prevMetatileBehavior != curMetatileBehavior && !AllowWildCheckOnNewMetatile())
                return FALSE;
            else if (WildEncounterCheck(gWildMonHeaders[headerId].waterMonsInfo->encounterRate, FALSE) != TRUE)
                return FALSE;

            if (TryStartRoamerEncounter() == TRUE)
            {
                roamer = &gSaveBlock1Ptr->roamer;
                if (!IsWildLevelAllowedByRepel(roamer->level))
                    return FALSE;

                BattleSetup_StartRoamerBattle();
                return TRUE;
            }
            else // try a regular surfing encounter
            {
                if (TryGenerateWildMon(gWildMonHeaders[headerId].waterMonsInfo, WILD_AREA_WATER, WILD_CHECK_REPEL | WILD_CHECK_KEEN_EYE) == TRUE)
                {
                    gIsSurfingEncounter = TRUE;
                    if (TryDoDoubleWildBattle())
                    {
                        struct Pokemon mon1 = gEnemyParty[0];
                        TryGenerateWildMon(gWildMonHeaders[headerId].waterMonsInfo, WILD_AREA_WATER, WILD_CHECK_KEEN_EYE);
                        gEnemyParty[1] = mon1;
                        BattleSetup_StartDoubleWildBattle();
                    }
                    else
                    {
                        BattleSetup_StartWildBattle();
                    }
                    return TRUE;
                }

                return FALSE;
            }
        }
    }

    return FALSE;
}

void RockSmashWildEncounter(void)
{
    u16 headerId = GetCurrentMapWildMonHeaderId();

    if (headerId != HEADER_NONE)
    {
        const struct WildPokemonInfo *wildPokemonInfo = gWildMonHeaders[headerId].rockSmashMonsInfo;

        if (wildPokemonInfo == NULL)
        {
            gSpecialVar_Result = FALSE;
        }
        else if (WildEncounterCheck(wildPokemonInfo->encounterRate, TRUE) == TRUE
         && TryGenerateWildMon(wildPokemonInfo, WILD_AREA_ROCKS, WILD_CHECK_REPEL | WILD_CHECK_KEEN_EYE) == TRUE)
        {
            BattleSetup_StartWildBattle();
            gSpecialVar_Result = TRUE;
        }
        else
        {
            gSpecialVar_Result = FALSE;
        }
    }
    else
    {
        gSpecialVar_Result = FALSE;
    }
}

bool8 SweetScentWildEncounter(void)
{
    s16 x, y;
    u16 headerId;

    PlayerGetDestCoords(&x, &y);
    headerId = GetCurrentMapWildMonHeaderId();
    if (headerId == HEADER_NONE)
    {
        if (gMapHeader.mapLayoutId == LAYOUT_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS)
        {
            headerId = GetBattlePikeWildMonHeaderId();
            if (TryGenerateWildMon(gBattlePikeWildMonHeaders[headerId].landMonsInfo, WILD_AREA_LAND, 0) != TRUE)
                return FALSE;

            TryGenerateBattlePikeWildMon(FALSE);
            BattleSetup_StartBattlePikeWildBattle();
            return TRUE;
        }
        if (gMapHeader.mapLayoutId == LAYOUT_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR)
        {
            headerId = gSaveBlock2Ptr->frontier.curChallengeBattleNum;
            if (TryGenerateWildMon(gBattlePyramidWildMonHeaders[headerId].landMonsInfo, WILD_AREA_LAND, 0) != TRUE)
                return FALSE;

            GenerateBattlePyramidWildMon();
            BattleSetup_StartWildBattle();
            return TRUE;
        }
    }
    else
    {
        if (MetatileBehavior_IsLandWildEncounter(MapGridGetMetatileBehaviorAt(x, y)) == TRUE)
        {
            if (gWildMonHeaders[headerId].landMonsInfo == NULL)
                return FALSE;

            if (TryStartRoamerEncounter() == TRUE)
            {
                BattleSetup_StartRoamerBattle();
                return TRUE;
            }

            if (DoMassOutbreakEncounterTest() == TRUE)
                SetUpMassOutbreakEncounter(0);
            else
                TryGenerateWildMon(gWildMonHeaders[headerId].landMonsInfo, WILD_AREA_LAND, 0);

            BattleSetup_StartWildBattle();
            return TRUE;
        }
        else if (MetatileBehavior_IsWaterWildEncounter(MapGridGetMetatileBehaviorAt(x, y)) == TRUE)
        {
            if (AreLegendariesInSootopolisPreventingEncounters() == TRUE)
                return FALSE;
            if (gWildMonHeaders[headerId].waterMonsInfo == NULL)
                return FALSE;

            if (TryStartRoamerEncounter() == TRUE)
            {
                BattleSetup_StartRoamerBattle();
                return TRUE;
            }

            TryGenerateWildMon(gWildMonHeaders[headerId].waterMonsInfo, WILD_AREA_WATER, 0);
            BattleSetup_StartWildBattle();
            return TRUE;
        }
    }

    return FALSE;
}

bool8 DoesCurrentMapHaveFishingMons(void)
{
    u16 headerId = GetCurrentMapWildMonHeaderId();

    if (headerId != HEADER_NONE && gWildMonHeaders[headerId].fishingMonsInfo != NULL)
        return TRUE;
    else
        return FALSE;
}

void FishingWildEncounter(u8 rod)
{
    u16 species;

    if (CheckFeebas() == TRUE)
    {
        u8 level = ChooseWildMonLevel(&sWildFeebas, 0, WILD_AREA_FISHING);

        species = sWildFeebas.species;
        CreateWildMon(species, level);
    }
    else
    {
        species = GenerateFishingWildMon(gWildMonHeaders[GetCurrentMapWildMonHeaderId()].fishingMonsInfo, rod);
    }
    IncrementGameStat(GAME_STAT_FISHING_ENCOUNTERS);
    SetPokemonAnglerSpecies(species);
    gIsFishingEncounter = TRUE;
    BattleSetup_StartWildBattle();
}

u16 GetLocalWildMon(bool8 *isWaterMon)
{
    u16 headerId;
    const struct WildPokemonInfo *landMonsInfo;
    const struct WildPokemonInfo *waterMonsInfo;

    *isWaterMon = FALSE;
    headerId = GetCurrentMapWildMonHeaderId();
    if (headerId == HEADER_NONE)
        return SPECIES_NONE;
    landMonsInfo = gWildMonHeaders[headerId].landMonsInfo;
    waterMonsInfo = gWildMonHeaders[headerId].waterMonsInfo;
    // Neither
    if (landMonsInfo == NULL && waterMonsInfo == NULL)
        return SPECIES_NONE;
    // Land Pokémon
    else if (landMonsInfo != NULL && waterMonsInfo == NULL)
        return landMonsInfo->wildPokemon[ChooseWildMonIndex_Land()].species;
    // Water Pokémon
    else if (landMonsInfo == NULL && waterMonsInfo != NULL)
    {
        *isWaterMon = TRUE;
        return waterMonsInfo->wildPokemon[ChooseWildMonIndex_WaterRock()].species;
    }
    // Either land or water Pokémon
    if ((Random() % 100) < 80)
    {
        return landMonsInfo->wildPokemon[ChooseWildMonIndex_Land()].species;
    }
    else
    {
        *isWaterMon = TRUE;
        return waterMonsInfo->wildPokemon[ChooseWildMonIndex_WaterRock()].species;
    }
}

u16 GetLocalWaterMon(void)
{
    u16 headerId = GetCurrentMapWildMonHeaderId();

    if (headerId != HEADER_NONE)
    {
        const struct WildPokemonInfo *waterMonsInfo = gWildMonHeaders[headerId].waterMonsInfo;

        if (waterMonsInfo)
            return waterMonsInfo->wildPokemon[ChooseWildMonIndex_WaterRock()].species;
    }
    return SPECIES_NONE;
}

bool8 UpdateRepelCounter(void)
{
    u16 repelLureVar = VarGet(VAR_REPEL_STEP_COUNT);
    u16 steps = REPEL_LURE_STEPS(repelLureVar);
    bool32 isLure = IS_LAST_USED_LURE(repelLureVar);

    if (InBattlePike() || InBattlePyramid())
        return FALSE;
    if (InUnionRoom() == TRUE)
        return FALSE;

    if (steps != 0)
    {
        steps--;
        if (!isLure)
        {
            VarSet(VAR_REPEL_STEP_COUNT, steps);
            if (steps == 0)
            {
                ScriptContext_SetupScript(EventScript_SprayWoreOff);
                return TRUE;
            }
        }
        else
        {
            VarSet(VAR_REPEL_STEP_COUNT, steps | REPEL_LURE_MASK);
            if (steps == 0)
            {
                ScriptContext_SetupScript(EventScript_SprayWoreOff);
                return TRUE;
            }
        }

    }
    return FALSE;
}

static bool8 IsWildLevelAllowedByRepel(u8 wildLevel)
{
    u8 i;

    if (!REPEL_STEP_COUNT)
        return TRUE;

    for (i = 0; i < PARTY_SIZE; i++)
    {
        if (GetMonData(&gPlayerParty[i], MON_DATA_HP) && !GetMonData(&gPlayerParty[i], MON_DATA_IS_EGG))
        {
            u8 ourLevel = GetMonData(&gPlayerParty[i], MON_DATA_LEVEL);

            if (wildLevel < ourLevel)
                return FALSE;
            else
                return TRUE;
        }
    }

    return FALSE;
}

static bool8 IsAbilityAllowingEncounter(u8 level)
{
    u16 ability;

    if (GetMonData(&gPlayerParty[0], MON_DATA_SANITY_IS_EGG))
        return TRUE;

    ability = GetMonAbility(&gPlayerParty[0]);
    if (ability == ABILITY_KEEN_EYE || ability == ABILITY_INTIMIDATE)
    {
        u8 playerMonLevel = GetMonData(&gPlayerParty[0], MON_DATA_LEVEL);
        if (playerMonLevel > 5 && level <= playerMonLevel - 5 && !(Random() % 2))
            return FALSE;
    }

    return TRUE;
}

static bool8 TryGetRandomWildMonIndexByType(const struct WildPokemon *wildMon, u8 type, u8 numMon, u8 *monIndex)
{
    u8 validIndexes[numMon]; // variable length array, an interesting feature
    u8 i, validMonCount;

    for (i = 0; i < numMon; i++)
        validIndexes[i] = 0;

    for (validMonCount = 0, i = 0; i < numMon; i++)
    {
        if (gSpeciesInfo[wildMon[i].species].types[0] == type || gSpeciesInfo[wildMon[i].species].types[1] == type)
            validIndexes[validMonCount++] = i;
    }

    if (validMonCount == 0 || validMonCount == numMon)
        return FALSE;

    *monIndex = validIndexes[Random() % validMonCount];
    return TRUE;
}

#include "data.h"

static u8 GetMaxLevelOfSpeciesInWildTable(const struct WildPokemon *wildMon, u16 species, u8 area)
{
    u8 i, maxLevel = 0, numMon = 0;

    switch (area)
    {
    case WILD_AREA_LAND:
        numMon = LAND_WILD_COUNT;
        break;
    case WILD_AREA_WATER:
        numMon = WATER_WILD_COUNT;
        break;
    case WILD_AREA_ROCKS:
        numMon = ROCK_WILD_COUNT;
        break;
    }

    for (i = 0; i < numMon; i++)
    {
        if (wildMon[i].species == species && wildMon[i].maxLevel > maxLevel)
            maxLevel = wildMon[i].maxLevel;
    }

    return maxLevel;
}

#ifdef BUGFIX
static bool8 TryGetAbilityInfluencedWildMonIndex(const struct WildPokemon *wildMon, u8 type, u16 ability, u8 *monIndex, u32 size)
#else
static bool8 TryGetAbilityInfluencedWildMonIndex(const struct WildPokemon *wildMon, u8 type, u16 ability, u8 *monIndex)
#endif
{
    if (GetMonData(&gPlayerParty[0], MON_DATA_SANITY_IS_EGG))
        return FALSE;
    else if (GetMonAbility(&gPlayerParty[0]) != ability)
        return FALSE;
    else if (Random() % 2 != 0)
        return FALSE;

#ifdef BUGFIX
    return TryGetRandomWildMonIndexByType(wildMon, type, size, monIndex);
#else
    return TryGetRandomWildMonIndexByType(wildMon, type, LAND_WILD_COUNT, monIndex);
#endif
}

static void ApplyFluteEncounterRateMod(u32 *encRate)
{
    if (FlagGet(FLAG_SYS_ENC_UP_ITEM) == TRUE)
        *encRate += *encRate / 2;
    else if (FlagGet(FLAG_SYS_ENC_DOWN_ITEM) == TRUE)
        *encRate = *encRate / 2;
}

static void ApplyCleanseTagEncounterRateMod(u32 *encRate)
{
    if (GetMonData(&gPlayerParty[0], MON_DATA_HELD_ITEM) == ITEM_CLEANSE_TAG)
        *encRate = *encRate * 2 / 3;
}

bool8 TryDoDoubleWildBattle(void)
{
    if (GetSafariZoneFlag()
      || (B_DOUBLE_WILD_REQUIRE_2_MONS == TRUE && GetMonsStateToDoubles() != PLAYER_HAS_TWO_USABLE_MONS))
        return FALSE;
    else if (B_FLAG_FORCE_DOUBLE_WILD != 0 && FlagGet(B_FLAG_FORCE_DOUBLE_WILD))
        return TRUE;
    else if (B_DOUBLE_WILD_CHANCE != 0 && ((Random() % 100) + 1 <= B_DOUBLE_WILD_CHANCE))
        return TRUE;
    return FALSE;
}

bool8 StandardWildEncounter_Debug(void)
{
    u16 headerId = GetCurrentMapWildMonHeaderId();
    if (TryGenerateWildMon(gWildMonHeaders[headerId].landMonsInfo, WILD_AREA_LAND, 0) != TRUE)
        return FALSE;

    DoStandardWildBattle_Debug();
    return TRUE;
}
